[toolchain]
anchor_version = "0.30.0"

[features]
skip-lint = false
seeds = true

[programs.devnet]
# sol_xen_minter = "7Ltcx8X3twQnfYtmCs3C6PTUPhPcZkr1opEoxjFz4xDN"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "http://69.10.34.226:8899"
# cluster = "https://api.mainnet-beta.solana.com"
cluster = "https://skilled-lingering-wish.solana-mainnet.quiknode.pro/3e1dae8f5b3c9f83e29742f504e527e696bff22a/"
# cluster = "devnet"
# cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
